[wicket-scala] Upgrade specs version to allow get tests to pass
For some reason the build was failing due to these errors:

org.apache.wicket.WicketRuntimeException: Unable to create org.apache.wicket.extensions.Initializer

By upgrading to the latest specs version the error went away.